# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      if: hashFiles('package-lock.json') != ''
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      if: hashFiles('package-lock.json') != ''

    - name: Build
      run: npm run build --if-present
      if: hashFiles('package-lock.json') != ''

    - name: Test
      run: npm test
      if: hashFiles('package-lock.json') != ''

    - name: Static site - no build needed
      run: echo "No Node.js build necessary"
      if: hashFiles('package-lock.json') == ''
